version: "3"
services:
  gqlgen-server:
    build:
      context: gqlgen-service
    expose:
      - 8080
  gophers-server:
    build:
      context: graph-gophers-service
    expose:
      - 8080
  nodejs-server:
    build:
      context: nodejs-service
    expose:
      - 8080
  gateway:
    image: ghcr.io/movio/bramble
    volumes:
      - ./example-config.json:/config.json
    ports:
      - 8082:8082
      - 8083:8083
      - 8084:8084
    depends_on:
      - gqlgen-server
      - gophers-server
      - nodejs-server
