name: Publish Docker image
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  push-to-ghcr:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set BRAMBLE_VERSION env
        run: echo "BRAMBLE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/movio/bramble

      - name: Push to ghcr.io
        uses: docker/build-push-action@v4
        with:
          context: .
          registry: ghcr.io
          push: true
          build-args: |
            VERSION=${{ env.BRAMBLE_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
