name: Notify Movio

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Movio
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MOVIO_ACTIONS_ACCESS }}
          repository: movio/bramble-movio
          event-type: ${{ github.event_name }}
          client-payload: |-
            {
              "repository": "${{ github.repository }}",
              "ref": "${{ github.ref }}",
              "ref_name": "${{ github.ref_name }}",
              "sha": "${{ github.sha }}"
            }
